sonar.projectKey=luizhammeli_Tets-Proj-CI
sonar.organization=luizhammeli
sonar.projectName=Tets-Proj-CI
sonar.qualitygate.wait=true
sonar.sources=Tets-Proj-CI
sonar.tests=Tets-Proj-CITests
sonar.language=swift
sonar.sourceEncoding=UTF-8
sonar.swift.coverage.reportPaths=coverage.lcov
sonar.exclusions=**/Pods/**,**/*.generated.swift,**/Mocks/**,.github/workflows/**,fastlane/**,**/*.xcodeproj/**,**/*.xcworkspace/**,**/DerivedData/**,**/Build/**,**/Products/**,**/sonar-project.properties, **/xccov-to-lcov.sh