default_platform(:ios)

lane :ci_lint do
  swiftlint(
    mode: :lint,        # ou :fix
    strict: true        # falha o build se houver warning/error
  )
end

# desc "Run Scheme Tets-Proj-CI"
# lane :ci_iOS do
#   scan(
#       clean: true,
#       scheme: "Tets-Proj-CI",
#       sdk: "iphonesimulator",
#       code_coverage: true,
#       result_bundle: true
#   )

#   derived_data = lane_context[SharedValues::SCAN_DERIVED_DATA_PATH]
#   profdata = Dir["#{derived_data}/Build/ProfileData/*/*.profdata"].first
#   UI.user_error!("profdata not found") unless profdata

#   test_bundle = Dir["#{derived_data}/Build/Products/**/*.xctest"].first
#   UI.user_error!("test bundle not found") unless test_bundle
#   test_binary = File.join(test_bundle, File.basename(test_bundle, ".xctest"))
#   UI.user_error!("test binary not found") unless File.exist?(test_binary)

#   app_bundle = Dir["#{derived_data}/Build/Products/**/*.app"].first
#   UI.user_error!("app binary not found") unless app_bundle
#   app_binary = File.join(app_bundle, File.basename(app_bundle, ".app"))
#   UI.user_error!("app binary not found") unless File.exist?(app_binary)
  
#   output_path = File.join(Dir.pwd, "coverage.lcov")
#   sh("xcrun llvm-cov export -format=lcov -instr-profile '#{profdata}' -object '#{test_binary}' -object '#{app_binary}'  > '#{output_path}'")
# end