default_platform(:ios)

lane :ci_lint do
  swiftlint(
    mode: :lint,        # ou :fix
    strict: true        # falha o build se houver warning/error
  )
end

desc "Run Scheme Tets-Proj-CI"
lane :ci_iOS do
  scan(
      clean: true,
      scheme: "Tets-Proj-CI",
      sdk: "iphonesimulator",
      device: 'iPhone 17 Pro (26.0)'

  )

  result = xcov(
    scheme: "Tets-Proj-CI",
    output_directory: "xcov_output",
    minimum_coverage_percentage: 80.0
  )

  report = xcov.produce_report(
  scheme: "Tets-Proj-CI",
  output_directory: "xcov_output",
  minimum_coverage_percentage: 80
  )

  xcov.output_report(report)

  coverage = result[:overall_coverage]
  UI.message("📈 Coverage total: #{coverage}%")
  
  ENV["XCOV_COVERAGE"] = coverage.to_s
end
