default_platform(:ios)

lane :swiftlint do
  swiftlint(
    mode: :lint,        # ou :fix
    strict: true        # falha o build se houver warning/error
  )
end

desc "Run Scheme Tets-Proj-CI"
lane :ci_iOS do
  scan(
      clean: true,
      scheme: "Tets-Proj-CI",
      sdk: "iphonesimulator",
      xcargs: "-destination 'platform=iOS Simulator,OS=26.0.1'"

  )
end